version: 2
jobs:
  build:
    branches:
      only:
        - development
      ignore:
        - gh-pages
        - master
    docker:
      - image: circleci/node:9.9.0
    working_directory: ~/repo

    steps:
      - checkout

#      - add_ssh_keys:
#          fingerprints:
#            - "27:d6:0b:7a:7c:4e:77:c8:76:4a:9a:c4:db:1b:c3:e7"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

#      - run: npm install
#      - run: npm run deploy
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "junrong09@users.noreply.github.com"
            git config --global user.name "junrong09"
            echo "machine github.com login junrong09 password $GITHUB_TOKEN" > ~/.netrc
            npm install
            npm run deploy

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
