version: 2
jobs:
  build:
    branches:
      only:
        - development
      ignore:
        - gh-pages
        - master
    docker:
      - image: circleci/node:9.9.0
    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "53:de:70:e7:e2:d4:bc:b6:81:15:e6:97:63:71:2a:92"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: git config user.email "junrongy09@gmail.com"
      - run: git config user.name "junrong09"
      - run: npm run deploy

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
