ersion: 2
jobs:
  build:
    branches:
      only:
        - development
    docker:
      - image: circleci/node:9.9.0
    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "ba:ae:d2:da:e4:53:d8:75:73:91:ee:3a:f3:41:ad:3a"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: git config user.email "sujayanjankar@gmail.com"
      - run: git config user.name "Sujay Anjankar"
      - run: npm run deploy

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test