version: 2
jobs:
  build:
    branches:
      only:
        - development
      ignore:
        - gh-pages
        - master
    docker:
      - image: circleci/node:9.9.0
    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "27:d6:0b:7a:7c:4e:77:c8:76:4a:9a:c4:db:1b:c3:e7"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: git config user.email "sujayanjankar@gmail.com"
      - run: git config user.name "Sujay Anjankar"
      - run: npm run deploy

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
